### PR TITLE
2024 theme update

### PR DESCRIPTION
**Pull request by jkcox**
- README update, dev instructions
- add Changelog
- reorganize src/ and dist/
- refactor gulp tasks
- fontawesome v6
- UDS Background Section block - new patterns
- Update Accordion, tabbed panels, side menu, horizontal card
- Update to unity-bootstrap-theme-v1.13.0, sass tokens update
- component-header v2.3.0
- 404 page searches search.asu.edu
- delete legacy/unused JS, PHP
- interactive cards
- glidejs ASU sass styles

### CODE REVIEW

**Comment by zainabD** [comment]
Is this ready for review?

**Comment by zainabD** [comment]
- [ ] 404 background image in is missing.

- [ ] UDS background gradient is broken, check E+I QA: https://entrepreneurship.qa.rtd.asu.edu/training-and-development-resources/ 

- [ ] Why was the 'scroll to div' file removed? It was used on the E+I website.

**Comment by zainabD** [comment]
- [ ] It looks like "float-right" class was removed from bootstrap5, but we have used this class in our websites. Can we add "float-right" class to our css files, so we don't' have to update all websites that are using that class.

**Comment by zainabD** [comment]
- [ ] Replacing the **uds-section-gradient** class with one of the overlay classes should fix the gradient issue. I have already replaced it on the E+I site, but let's make sure it's not being used on other websites before we can merge this branch in.
- [ ] @jkcox The ASU logo and mobio menu disappeared when logged in to WP admin, see examples on Biodesign QA, and E+I QA: 
Screenshot 2024-09-10 at 3 03 49 PM

**Comment by jkcox** [comment]
> * [ ]  Replacing the **uds-section-gradient** class with one of the overlay classes should fix the gradient issue. I have already replaced it on the E+I site, but let's make sure it's not being used on other websites before we can merge this branch in.
> * [ ]  @jkcox The ASU logo and mobile menu disappear when logged in to the WP admin. See examples on Biodesign QA and E+I QA:
> 


Ok I see what happed now - `position:sticky` was added because there is a gap between the main menu and top of window when scrolling where the admin bar would be located.

But for some reason at the top it is not sticky to top of window - should be able to find a solution.

**Pull request merged**
