### PR TITLE
UDS Hero v1 - Deprecation

### PR DESCRIPTION
**Pull request by SteveRyan-ASU**
This pull request should complete the process of deprecating the v1 hero. Changes included with this PR:

- The removal of the ACF JSON field groups for the v1 hero.
- The removal of the ACF JSON field group controlling the logic of the display of the page title within `single.php`.
- The logic that looked for a suitable featured image for a post by referencing the hero image from an assigned category has been removed.
- The template for the display of the v1 hero image has been relocated to a new folder within the theme called `templates-deprecated` It will continue to live within the theme until we determine that remediation efforts for the old hero block have been completed.

This PR is being issued along side of the initial release of the **UDS Deprecation Helper** plugin which accomplishes the following:

- Provides a theme options panel and a mechanism for this and future deprecations within the theme. 
- Conditionally loads the ACF JSON field groups for the v1 version of the hero images based on a site options setting.
- Conditionally allows the deprecated template files to be called within various templates within the theme.

The UDS Deprecation Helper plugin can be found here (for now). 

- https://github.com/asuengineering/UDS-WordPress-Deprecation-Helper

### CODE REVIEW

**Comment by SteveRyan-ASU** [comment]
Removed the `hero_video.js` JS file from the `functions.php / enqueue.php` stack and relocated to deprecation plugin. Now loaded conditionally based on the v1 hero option value.

**Comment by zainabD** [comment]
I was unable to activate the helper plugin. Here is the error I got: 
Plugin could not be activated because it triggered a fatal error.
I cannot find anything in the error log!
Screen Shot 2021-08-11 at 1 49 51 PM

**Comment by SteveRyan-ASU** [comment]
Problem with the plugin addressed. Released v0.1.1 with the bug fix in tow and a better README.md file to help document ongoing changes there. 

Link: https://github.com/asuengineering/UDS-WordPress-Deprecation-Helper

**Comment by SteveRyan-ASU** [comment]
Closing this pull request. This effort represents a process for deprecating and removing a block which may no longer be useful or correct for the UDS WordPress theme.

**Pull request closed without merging**
